name: Create Tag

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['packages/package.json']

env:
  ROBOT_NAME: ${{ github.actor }}
  ROBOT_EMAIL: ${{ github.actor }}@heathmont.net

jobs:
  create-tag:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
      
      - name: Get package version
        id: get_version
        run: |
          PACKAGE_VERSION=$(node -p "require('./packages/package.json').version")
          echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$PACKAGE_VERSION" >> $GITHUB_OUTPUT
          echo "Package version: $PACKAGE_VERSION"
      
      - name: Check if tag already exists
        id: check_tag
        run: |
          if git rev-parse "v${{ steps.get_version.outputs.version }}" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Tag v${{ steps.get_version.outputs.version }} already exists"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Tag v${{ steps.get_version.outputs.version }} does not exist, will create it"
          fi
      
      - name: Create and push tag
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          git config user.name "${{ env.ROBOT_NAME }}"
          git config user.email "${{ env.ROBOT_EMAIL }}"
          git tag -a "${{ steps.get_version.outputs.tag }}" -m "Release ${{ steps.get_version.outputs.tag }}"
          git push origin "${{ steps.get_version.outputs.tag }}"
          echo "✅ Successfully created and pushed tag ${{ steps.get_version.outputs.tag }}"
      
      - name: Tag already exists
        if: steps.check_tag.outputs.exists == 'true'
        run: echo "⚠️ Tag v${{ steps.get_version.outputs.version }} already exists, skipping tag creation"
